name: bench
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - awscli
  - bcftools
  - mamba
  - samtools
  - pip:
    - dysgu-1.8.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
    - cuteSV==2.1.2
    - sniffles==2.6.2
    - Truvari==5.3.0
    - plotly==5.24.1
    - matplotlib
    - seaborn
    - pandas
    - tabulate
